---
title: "hpc_notebook"
output: html_notebook
---

This R notebook aims to explore the potential applications of [grow-shrink](https://doi.org/10.48550/arXiv.1407.8088)

This notebook utilizes the bnlearn library for its implementation of hpc.

```{r}
library(grid)
library(graph)
library(BiocGenerics)
library(Rgraphviz)
library(bnlearn)
library(readr)
```

Getting the data from csv files stored locally on device

```{r}
# Dubee
path_lsds_15 <- file.choose()
data_lsds_15 <- read.csv(path_lsds_15, header = TRUE)
data2_lsds_15 <- read.csv(path_lsds_15, header = FALSE)
```

```{r}
# Keune 2015
path_lsds_9 <- file.choose()
data_lsds_9 <- read.csv(path_lsds_9, header = FALSE)
```

```{r}
# Keune 2016
path_lsds_30 <- file.choose()
data_lsds30 <- read.csv(path_lsds_30, header = FALSE)
```

```{r}
# Ko 2020 1 of 2
path_lsds_41 <- file.choose()
data_lsds41 <- read.csv(path_lsds_41, header = FALSE)
```

```{r}
# Ko 2020 2 of 2
# micro ct
path_mct_lsds_40 <- file.choose()
# histomorphometry
path_hist_lsds_40 <- file.choose()
# bone
path_bone_lsds_40 <- file.choose()

data_mct_lsds_40 <- read.csv(path_mct_lsds_40, header = FALSE)
data_hist_lsds40 <- read.csv(path_hist_lsds_40, header = FALSE)
data_bone_lsds40 <- read.csv(path_bone_lsds_40, header = FALSE)
```

To start Convert it to a dataframe.

```{r}
# Manipulate dataset
data_lsds_15 <- as.data.frame(data_lsds_15)


data <- data_lsds_15
dsub_set <- subset(data, select=-(1:2))
dsub_set$Factor.Value <- as.numeric(factor(dsub_set$Factor.Value, levels = unique(dsub_set$Factor.Value)))


dsub_set

```

Looks good! Let's run growshrink

```{r}
# Identify character columns
char_columns <- sapply(data_lsds_15, is.character)

# Convert character columns to factors
data_lsds_15[char_columns] <- lapply(data_lsds_15[char_columns], as.factor)

data_lsds_15
```

```{r}
df <- data_lsds_15

excluded_columns <- c("Source.Name", "Sample.Name")
column_indices <- which(names(df) %in% excluded_columns)
df_subset <- df[, -column_indices]

```


```{r}
# dag <- bnlearn::hpc(df_subset)
dag <- bnlearn::hpc(dsub_set)

graph_dag <- bnlearn::as.graphNEL(dag)



# Increase the resolution and size of the plot
png("graph_dag.png", width = 2400, height = 1600, res = 600)
plot(graph_dag)
dev.off()


```

```{r}
# Using DiagrammeR to graph instead

# Install and load the DiagrammeR package
install.packages("DiagrammeR")
install.packages("DiagrammeRsvg")
install.packages('rsvg')
library(DiagrammeR)

# Convert the bnlearn DAG to a DiagrammeR graph
graph <- create_graph()

# Add nodes to the graph
nodes <- graph_dag@nodes
for (node_name in nodes) {
  graph <- graph %>% add_node(label = node_name)
}

# Add edges to the graph
edges <- edges(graph_dag)
for (from_node in names(edges)) {
  from_node <- as.character(edge)
  
  for (to_node in edges[from_node]) {
    to_node <- as.character(to_node)
    graph <- graph %>% add_edge(graph, from = from_node, to = to_node)
  
    # add_edge(graph, from = from_node, to = to_node)
  }
}

for (edge in names(edges))
  print("as.character(edge)")



# Adjust the font size of the nodes
graph_dag %>% 
  graph_attrs(fontsize = 14) %>%  # Set the desired font size
  node_attrs(fontsize = 14)       # Set the desired font size


graph %>% get_node_ids()
graph %>% count_nodes()
graph %>% get_node_df()
graph %>% count_edges()
#> [1] 2


export_graph(graph, file_name= "test.png",file_type = "PNG")

```
